id: P010803
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-20 10:25:15.064618
source_metadata:
  id: bdr:W29902
  title: དཔལ་ཀྱེ་རྡོ་རྗེའི་རྒྱུད་ཀྱི་བཤད་པ་བཀའི་བརྒྱ་པ་རིན་པོ་ཆེ་ལ་གསོལ་བ་འདེབས་པ
  author: ''
  volumes:
    1b4110a4b08b4c60b5e0732a9a470070:
      image_group_id: I5737
      title: ''
      volume_number: 1
      total_pages: 532
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
