id: I8E9898FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T04:08:14+00:00'
last_modified: '2022-06-08T17:38:22.595176+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29902
  title: དཔལ་ཀྱེ་རྡོ་རྗེའི་རྒྱུད་ཀྱི་བཤད་པ་བཀའི་བརྒྱ་པ་རིན་པོ་ཆེ་ལ་གསོལ་བ་འདེབས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4B54:
      image_group_id: I5737
      title: ''
      total_pages: 532
      order: 1
      base_file: 4B54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
